# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for WhisperEngine Desktop App - Linux
Generated by cross-platform build system.
"""

import os
from pathlib import Path

# Application paths
app_path = Path.cwd()
src_path = app_path / "src"
ui_path = src_path / "ui"

block_cipher = None

# Data files (templates, static assets)
data_files = []

# Hidden imports (modules not automatically detected)
hidden_imports = ['sqlite3', 'json', 'asyncio', 'logging', 'threading', 'signal', 'pystray', 'PIL', 'PIL.Image', 'PIL.ImageDraw', 'src.ui.system_tray', 'src.config.adaptive_config', 'src.database.database_integration', 'src.optimization.cost_optimizer', 'src.core.native_ai_service', 'src.platforms.universal_chat', 'gi', 'gi.repository', 'gi.repository.Gtk', 'gi.repository.GLib']

a = Analysis(
    ['universal_native_app.py'],
    pathex=[str(app_path)],
    binaries=[],
    datas=data_files,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy', 'PIL.ImageTk', 'PIL.ImageWin', 'PIL.ImageQt', 'test_*', 'tests'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='WhisperEngine',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='WhisperEngine',
)
